language: scala

scala:
- 2.12.1
- 2.11.8

jdk:
- oraclejdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

env:
  global:
    JSENV=node

script:
  - sbt ++$TRAVIS_SCALA_VERSION test:fastOptJS test:fullOptJS
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' test
  - sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' 'set scalaJSStage in ThisBuild := FullOptStage' test


deploy:
  provider: script
  script:
  - /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt ++$TRAVIS_SCALA_VERSION publish
  on:
    tags: true

env:
  global:
  # travis encrypt BINTRAY_USER=xxx
  - secure: "jgRLCmNSINwbLtWlSh0HzUkLrim+lMHzya9WzY3eYlLxZKkZBsxs06fG15qCrJqCrMGOi/Zwy0vKCL6GSnyDCqUfNkoduuelQ2wGvjlRb2xTloXwmkAuLDMUxNEhIB0EbHnT0IMmdd3+12r8Q6gKGRn6/1PcqKxaheJA4ybxQNgY/jv2Cewd0YyTlJeoLdn4F0CY2ejB17MRPJs2vblt9jilvjPCJcK6ARX6W/aJ/7OqX+LDGi84/L1fVrOzr6eZ4UBBkkxn8pGIk8SBfKJiFrN3Ogm7piJ6kjooFPvE8EPY4fMk7srm1kTZsySDkHv9x1eSWoUNAraKgO+Mowt8Rc9llrc26GQe12Js2+fA6sB5YFelQ+DRKUi8I7vIvqUW/nR22c5QQ6qn0YWLrWhTDZrXA5QTEkRZrEWnmuvFpfxeqNt042xJVJZR2n8J9D1CF/6AgsolGgF+JPKwHvizGX3RdIGaPVM6ywgsFKqgS07VRX2yLbgSaLwxylUNVo1fAJFXmKU3ySYBaoWcqpHNgazlYnoUt1Zd9uoL52Ir3Zj341PXeCA40dq5v60xQMG9H3iW4PFavr03sbLfXwpU3UV2v+1OlqpMegljLyKwUneb3C/EI69PLjzTcIaObO5AhzzYCdVbQZxvXaO1ZqPlcu828bfUzbF3mVo7DOc1rGQ="
  # travis encrypt BINTRAY_PASSWORD=xxx
  - secure: "LDnjt85BWNEqHrI+2FkSe9AJxeIlnfUXxPU6Tw7fY7JfsJ06aSZ+A9uCJ5MymxEkUPnx22OoJvAdMnlPewuHhBvr2UUgTML03B0l92qlyclNPBgpqcosBoIgp0L47Yng5KV+LUIQzeuKAPxRKw/QaH6i//CecShNQcBBb483p8SXB+TGua74I9g8O9zdu09meCiFw10HpqBmcp8GfqUln9mzWfPpyl/qc0aL6XVV/Bx6Xuq7/KyjhuV6QDZBby81jbq4VQ3OJwU28jrhXQ8xIVDn8SUyDZTJPgPTnHXRyCMjTsQ8F1sWPMpDqZpnUKgwRhXEqNm8f+iJBPLIYaoCUf1Zla2B2vhi5cYh0053lfQmFYsgBoOJjJdj4RH5OaI8HROkbc+JIqEhBBfYfaY0f+WwDju70POwU0BcfBHfhOhbJSeldvax10oXs8lbbYsQH4sN/Lg1TgpgnAUFXoIYFL1z7t8eO+kcqMIuEaOSclSnkrx37NLbmGETZ8cHew9ZUB7e+ObaGXVVDgkvhLbvtMMbWORp66cz3vYBvPutDO9qp6anNPom+qoL7HDrVik1pCVCSyDvsPQuhSDRzxvIThh8f22nsrNvJJ70Utxn/gGZHVrQi2luuOkSfH06XxiuthPBPK326d4jfqYO7Ffb7LuDLdXee4wtNFtYiYEZhxk="

